const trainingData = [
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
];

// The target attribute (the class we are trying to predict)
const targetAttribute = "COLLEGE";

/*
 * Counts the frequency of each unique value for a given attribute in a dataset.
 * @param {Array<Object>} data The dataset (array of objects).
 * @param {string} attribute The attribute name (key in the objects).
 * @returns {Object} A map of value -> count.
 */

function countFrequencies(data, attribute) {
  const counts = {}; // store count of each attribute
  for (const example of data) {
    const value = example[attribute];
    counts[value] = (counts[value] || 0) + 1;
  }
  // console.log(counts);
  return counts;
}

/*
 * Calculates the Entropy of the dataset based on the target attribute.
 * @param {Array<Object>} data The dataset.
 * @param {string} targetAttr The name of the target/class attribute.
 * @returns {number} The calculated entropy.
 */

function calculateEntropy(data, targetAttr) {
  if (data.length === 0) {
    return 0; // No data, no impurity
  }
  const classCounts = countFrequencies(data, targetAttr);
  const totalExamples = data.length;
  let entropy = 0;

  for (const count of Object.values(classCounts)) {
    const probability = count / totalExamples;
    // Handle log2(0) case: p * log2(p) is 0 when p is 0.
    // Since we only iterate over counts > 0, we don't need a special check here.
    entropy -= probability * Math.log2(probability);
  }
  return entropy;
}

// Example usage:
console.log(
  "Initial Entropy:",
  calculateEntropy(trainingData, targetAttribute)
);

/*
 * Splits the dataset into subsets based on the values of a given attribute.
 * @param {Array<Object>} data The dataset.
 * @param {string} attribute The attribute name to split on.
 * @returns {Object<string, Array<Object>>} A map of attribute_value -> subset_data.
 */
function splitData(data, attribute) {
  const subsets = {};
  for (const example of data) {
    const value = example[attribute];
    if (!subsets[value]) {
      subsets[value] = [];
    }
    subsets[value].push(example);
  }
  return subsets;
}

/*
 * Calculates the Information Gain for splitting the dataset by a given attribute.
 * @param {Array<Object>} data The dataset.
 * @param {string} attribute The attribute to calculate gain for.
 * @param {string} targetAttr The target attribute name.
 * @returns {number} The calculated Information Gain.
 */
function calculateInformationGain(data, attribute, targetAttr) {
  const initialEntropy = calculateEntropy(data, targetAttr);
  const subsets = splitData(data, attribute);
  const totalExamples = data.length;
  let remainingEntropy = 0;

  for (const subsetData of Object.values(subsets)) {
    const proportion = subsetData.length / totalExamples;
    const subsetEntropy = calculateEntropy(subsetData, targetAttr);
    remainingEntropy += proportion * subsetEntropy;
  }

  return initialEntropy - remainingEntropy;
}

/*
 * Finds the attribute that results in the highest Information Gain.
 * @param {Array<Object>} data The dataset.
 * @param {Array<string>} attributes The list of attributes to consider (excluding target).
 * @param {string} targetAttr The target attribute name.
 * @returns {string | null} The best attribute name, or null if no attributes are left.
 */
function findBestSplitAttribute(data, attributes, targetAttr) {
  let maxGain = -Infinity;
  let bestAttribute = null;

  for (const attribute of attributes) {
    const gain = calculateInformationGain(data, attribute, targetAttr);

    // Check for ties: we can just pick the first one found.
    if (gain > maxGain) {
      maxGain = gain;
      bestAttribute = attribute;
    }
  }

  return bestAttribute;
}

const attributes = [
  "SEE_GPA",
  "SEE_Science_GPA",
  "SEE_Math_GPA",
  "Fee",
  "Hostel",
  "Transportation",
  "ECA",
  "Scholarship",
  "Science_Labs",
  "Infrastructure",
];

console.log(
  "Best Initial Attribute:",
  findBestSplitAttribute(trainingData, attributes, targetAttribute)
);

/*
 * Finds the most frequent class in a dataset.
 * @param {Array<Object>} data The dataset.
 * @param {string} targetAttr The target attribute name.
 * @returns {string} The majority class label.
 */
function getMajorityClass(data, targetAttr) {
  const classCounts = countFrequencies(data, targetAttr);
  let majorityClass = null;
  let maxCount = -1;

  for (const [className, count] of Object.entries(classCounts)) {
    if (count > maxCount) {
      maxCount = count;
      majorityClass = className;
    }
  }
  return majorityClass;
}

const majority = getMajorityClass(trainingData, "COLLEGE");
console.log(majority);

/*
 * Recursively builds the ID3 decision tree.
 * @param {Array<Object>} data The current subset of the training data.
 * @param {Array<string>} availableAttributes The attributes remaining to be split on.
 * @param {string} targetAttr The target attribute name.
 * @returns {Object} The tree node (internal node or leaf node).
 */
function buildID3Tree(data, availableAttributes, targetAttr) {
  // 1. **Base Case 1: All examples are of the same class (Pure Node)**
  // If the entropy is 0, we have a pure set.
  if (calculateEntropy(data, targetAttr) === 0) {
    // The class is the value of the target attribute of the first example
    return { type: "leaf", class: data[0][targetAttr] };
  }

  // 2. **Base Case 2: No attributes left**
  if (availableAttributes.length === 0) {
    // Return a leaf node with the majority class
    return { type: "leaf", class: getMajorityClass(data, targetAttr) };
  }

  // 3. **Recursive Step: Find the best split**
  const bestAttribute = findBestSplitAttribute(
    data,
    availableAttributes,
    targetAttr
  );

  // If bestAttribute is null (e.g., all remaining attributes have 0 gain), use majority class
  if (!bestAttribute) {
    return { type: "leaf", class: getMajorityClass(data, targetAttr) };
  }

  // Create a new node for the tree
  const tree = {
    type: "node",
    attribute: bestAttribute,
    children: {},
  };

  // Remove the chosen attribute from the list for the next recursive calls
  const remainingAttributes = availableAttributes.filter(
    (attr) => attr !== bestAttribute
  );
  const subsets = splitData(data, bestAttribute);

  // 4. **Recursive Call for each subset**
  for (const [value, subset] of Object.entries(subsets)) {
    // If the subset is empty (unlikely with this data structure, but good for robustness),
    // it becomes a leaf node of the majority class of the parent data.
    if (subset.length === 0) {
      tree.children[value] = {
        type: "leaf",
        class: getMajorityClass(data, targetAttr),
      };
    } else {
      // Build the subtree recursively
      tree.children[value] = buildID3Tree(
        subset,
        remainingAttributes,
        targetAttr
      );
    }
  }

  return tree;
}

// Get all unique attributes except the target
/* const allAttributes = Object.keys(trainingData[0]).filter(
  (attr) => attr !== targetAttribute
); */

// Build the tree
const decisionTree = buildID3Tree(trainingData, attributes, targetAttribute);

console.log("--- The final ID3 Decision Tree structure ---");
console.log(JSON.stringify(decisionTree, null, 2));

// --- Simple function to use the tree for a prediction ---
function classify(tree, example) {
  // If it's a leaf node, return the classification
  if (tree.type === "leaf") {
    return tree.class;
  }

  // It's an internal node. Get the attribute value for the current example.
  const attributeValue = example[tree.attribute];

  // Find the corresponding branch (child)
  const nextNode = tree.children[attributeValue];

  // Handle cases where the example has a value not seen in training (optional)
  if (!nextNode) {
    console.warn(
      `No branch for attribute value '${attributeValue}' on attribute '${tree.attribute}'. Using majority class of the parent node.`
    );
    // Fallback: return the majority class of the whole training set (a simplification)
    return getMajorityClass(trainingData, targetAttribute);
  }

  // Recurse down the tree
  return classify(nextNode, example);
}

// Test the classifier
const newExample = {
  SEE_GPA: "2.0-2.8",
  SEE_Science_GPA: "<2.4",
  SEE_Math_GPA: "<2.4",
  Fee: "Low",
  Hostel: "No",
  Transportation: "No",
  ECA: "Weak",
  Scholarship: "No",
  Science_Labs: "Poor",
  Infrastructure: "Poor",
};
const prediction = classify(decisionTree, newExample);

console.log("\n--- Prediction Test ---");
console.log("Example:", newExample);
console.log("Predicted Class:", prediction);

const testData = [
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
];

/*
 * Builds a generic Confusion Matrix for a multi-class classifier.
 * @param {Object} tree The trained ID3 decision tree structure.
 * @param {Array<Object>} testData The dataset to evaluate the model on.
 * @param {string} targetAttr The name of the target/class attribute.
 * @returns {Object} A structure representing the confusion matrix.
 */
function buildConfusionMatrix(tree, testData, targetAttr) {
  // 1. Identify all unique class labels
  const allActualClasses = new Set(testData.map((d) => d[targetAttr]));
  // We can also get all classes from the training set for completeness, but test set classes are the minimum needed.
  const uniqueClasses = Array.from(allActualClasses).sort(); // Sort for consistent order

  // 2. Initialize the Matrix structure
  // We'll use a nested object (Map) for easy access: matrix[Actual][Predicted]
  const matrix = {};
  for (const actualClass of uniqueClasses) {
    matrix[actualClass] = {};
    for (const predictedClass of uniqueClasses) {
      matrix[actualClass][predictedClass] = 0;
    }
  }

  // 3. Populate the Matrix by classifying each test example
  for (const example of testData) {
    const actual = example[targetAttr];
    // Note: We need the classify function from the previous step here.
    const predicted = classify(tree, example);

    // Handle a predicted class that might not be in the initial uniqueClasses set
    if (!matrix[actual] || !matrix[actual][predicted]) {
      // If 'predicted' class is new, add it to the matrix structure (robustness)
      if (matrix[actual]) {
        matrix[actual][predicted] = (matrix[actual][predicted] || 0) + 1;
      } else {
        // This case should not happen if all classes are captured, but it handles edge cases.
        // For simplicity, we assume 'actual' is always in the set.
        console.error(`Actual class '${actual}' not initialized.`);
      }
    } else {
      // Increment the count at the intersection of Actual (row) and Predicted (column)
      matrix[actual][predicted] += 1;
    }
  }

  return { matrix, uniqueClasses }; // Return classes to aid in printing/analysis
}

const { matrix, uniqueClasses } = buildConfusionMatrix(
  decisionTree,
  testData,
  targetAttribute
);

console.log("\n--- Generic Confusion Matrix ---");

// Helper function to format the matrix nicely
function printMatrix(matrix, classes) {
  // 1. Print Header Row
  let header = "ACTUAL \\ PREDICTED |";
  for (const pClass of classes) {
    header += ` ${pClass.padEnd(5)} |`; // Pad with spaces for alignment
  }
  console.log(header);
  console.log("-".repeat(header.length));

  // 2. Print Data Rows
  for (const aClass of classes) {
    let row = `${aClass.padEnd(20)}|`;
    for (const pClass of classes) {
      const count = matrix[aClass][pClass] || 0;
      row += ` ${String(count).padEnd(5)} |`;
    }
    console.log(row);
  }
}

printMatrix(matrix, uniqueClasses);

/**
 * Calculates generic classification metrics (Accuracy, Precision, Recall).
 */
function calculateMetrics(matrix, classes) {
  let totalCorrect = 0;
  let totalExamples = 0;

  // Aggregate data
  for (const aClass of classes) {
    for (const pClass of classes) {
      const count = matrix[aClass][pClass] || 0;
      totalExamples += count;
      if (aClass === pClass) {
        totalCorrect += count; // Diagonal is correct predictions
      }
    }
  }

  const accuracy = totalExamples > 0 ? totalCorrect / totalExamples : 0;

  const classMetrics = {};

  for (const targetClass of classes) {
    // True Positive (TP): Actual is targetClass AND Predicted is targetClass
    const TP = matrix[targetClass][targetClass] || 0;

    // False Positive (FP): Actual is NOT targetClass BUT Predicted IS targetClass
    let FP = 0;
    for (const aClass of classes) {
      if (aClass !== targetClass) {
        FP += matrix[aClass][targetClass] || 0;
      }
    }

    // False Negative (FN): Actual IS targetClass BUT Predicted is NOT targetClass
    let FN = 0;
    for (const pClass of classes) {
      if (pClass !== targetClass) {
        FN += matrix[targetClass][pClass] || 0;
      }
    }

    // Precision: TP / (TP + FP) -> How many predicted as targetClass were correct?
    const precisionDenominator = TP + FP;
    const precision = precisionDenominator > 0 ? TP / precisionDenominator : 0;

    // Recall: TP / (TP + FN) -> How many actual targetClass were correctly identified?
    const recallDenominator = TP + FN;
    const recall = recallDenominator > 0 ? TP / recallDenominator : 0;

    classMetrics[targetClass] = { TP, FP, FN, precision, recall };
  }

  return { accuracy, totalCorrect, totalExamples, classMetrics };
}

const metrics = calculateMetrics(matrix, uniqueClasses);

console.log("\n--- Evaluation Metrics ---");
console.log(`Total Examples: ${metrics.totalExamples}`);
console.log(`Total Correct: ${metrics.totalCorrect}`);
console.log(`Overall Accuracy: ${metrics.accuracy.toFixed(4)}`);

console.log("\nMetrics Per Class:");
for (const [className, classData] of Object.entries(metrics.classMetrics)) {
  console.log(`  Class '${className}':`);
  console.log(`    Precision: ${classData.precision.toFixed(4)}`);
  console.log(`    Recall:    ${classData.recall.toFixed(4)}`);
}
