const trainingData = [
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
];

const testData = [
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
];

// Attribute list
const attributes = [
  "SEE_GPA",
  "SEE_Science_GPA",
  "SEE_Math_GPA",
  "Fee",
  "Hostel",
  "Transportation",
  "ECA",
  "Scholarship",
  "Science_Labs",
  "Infrastructure",
];

// ----------------------
// ID3 Core Functions
// ----------------------

// count frequencies of attribute in data
function countFrequencies(data, attribute) {
  const counts = {};
  for (const ex of data) {
    const v = ex[attribute];
    counts[v] = (counts[v] || 0) + 1;
  }
  return counts;
}

// entropy of dataset with respect to targetAttr
function calculateEntropy(data, targetAttr) {
  if (!data || data.length === 0) return 0;
  const counts = countFrequencies(data, targetAttr);
  const total = data.length;
  let entropy = 0;
  for (const c of Object.values(counts)) {
    const p = c / total;
    entropy -= p * Math.log2(p);
  }
  return entropy;
}

// split dataset by attribute values
function splitData(data, attribute) {
  const subsets = {};
  for (const ex of data) {
    const val = ex[attribute];
    if (!subsets[val]) subsets[val] = [];
    subsets[val].push(ex);
  }
  return subsets;
}

// information gain
function calculateInformationGain(data, attribute, targetAttr) {
  const baseEntropy = calculateEntropy(data, targetAttr);
  const subsets = splitData(data, attribute);
  const total = data.length;
  let remainder = 0;
  for (const subset of Object.values(subsets)) {
    const w = subset.length / total;
    remainder += w * calculateEntropy(subset, targetAttr);
  }
  return baseEntropy - remainder;
}

// find best attribute
function findBestSplitAttribute(data, attrs, targetAttr) {
  let best = null;
  let bestGain = -Infinity;
  for (const a of attrs) {
    const gain = calculateInformationGain(data, a, targetAttr);
    if (gain > bestGain) {
      bestGain = gain;
      best = a;
    }
  }
  return best;
}

// majority class
function getMajorityClass(data, targetAttr) {
  const counts = countFrequencies(data, targetAttr);
  let best = null;
  let mx = -1;
  for (const [k, v] of Object.entries(counts)) {
    if (v > mx) {
      mx = v;
      best = k;
    }
  }
  return best;
}

// build ID3 tree
function buildID3Tree(data, availableAttributes, targetAttr) {
  if (!data || data.length === 0) return { type: "leaf", class: null };
  const ent = calculateEntropy(data, targetAttr);
  if (ent === 0) {
    return { type: "leaf", class: data[0][targetAttr] };
  }
  if (!availableAttributes || availableAttributes.length === 0) {
    return { type: "leaf", class: getMajorityClass(data, targetAttr) };
  }

  const bestAttr = findBestSplitAttribute(
    data,
    availableAttributes,
    targetAttr
  );
  if (!bestAttr)
    return { type: "leaf", class: getMajorityClass(data, targetAttr) };

  const node = {
    type: "node",
    attribute: bestAttr,
    majority: getMajorityClass(data, targetAttr),
    children: {},
  };
  const subsets = splitData(data, bestAttr);
  const remaining = availableAttributes.filter((a) => a !== bestAttr);

  for (const [val, subset] of Object.entries(subsets)) {
    if (!subset || subset.length === 0) {
      node.children[val] = {
        type: "leaf",
        class: getMajorityClass(data, targetAttr),
      };
    } else {
      node.children[val] = buildID3Tree(subset, remaining, targetAttr);
    }
  }
  return node;
}

// classify with tree; fallback to node.majority when unseen value
function classify(tree, example) {
  if (!tree) return null;
  if (tree.type === "leaf") return tree.class;
  const attr = tree.attribute;
  const val = example[attr];
  const child = tree.children[val];
  if (!child) return tree.majority !== undefined ? tree.majority : null;
  return classify(child, example);
}

// ----------------------
// Stage 1: Train TIER tree
// ----------------------
console.log("\n--- Training TIER tree ---");
const tierTree = buildID3Tree(trainingData, attributes, "TIER");
console.log("TIER tree built.");

// ----------------------
// Evaluate Stage 1 on test data (predict TIER)
// ----------------------
const tiers = ["Top", "Mid", "Low"];
function initMatrix(classes) {
  const mat = {};
  for (const a of classes) {
    mat[a] = {};
    for (const b of classes) mat[a][b] = 0;
  }
  return mat;
}

const tierMatrix = initMatrix(tiers);
let tierCorrect = 0;

const testPredictions = []; // store objects { example, predictedTier, predictedCollege (later) }

for (const ex of testData) {
  const predictedTier = classify(tierTree, ex);
  testPredictions.push({ example: ex, predictedTier, predictedCollege: null });
  // update tier confusion
  const actual = ex.TIER;
  if (!tierMatrix[actual]) tierMatrix[actual] = { Top: 0, Mid: 0, Low: 0 };
  tierMatrix[actual][predictedTier] =
    (tierMatrix[actual][predictedTier] || 0) + 1;
  if (predictedTier === actual) tierCorrect++;
}

function printMatrix(mat, classes) {
  const header = ["ACT\\PRED", ...classes];
  console.log("\n" + header.join("\t"));
  for (const a of classes) {
    const row = [a];
    for (const b of classes) row.push(String(mat[a][b] || 0));
    console.log(row.join("\t"));
  }
}

console.log("\n--- TIER Confusion Matrix ---");
printMatrix(tierMatrix, tiers);
console.log(
  `\nTIER Accuracy: ${tierCorrect}/${testData.length} = ${(
    (tierCorrect / testData.length) *
    100
  ).toFixed(2)}%`
);

// ----------------------
// Stage 2: Build COLLEGE trees per Tier (trained using trainingData filtered by TIER)
// ----------------------
console.log(
  "\n--- Training COLLEGE trees for each Tier (using training data filtered by TIER) ---"
);
const TOP_COLLEGES = ["KMC", "NIST", "Trinity", "St. Xavier"];
const MID_COLLEGES = ["Prime", "Times", "V.S Niketan", "Xavier Academy"];
const LOW_COLLEGES = ["Sagarmatha", "Takshashila", "Herald"];

const collegeTrees = {};
for (const tier of tiers) {
  const subset = trainingData.filter((r) => r.TIER === tier);
  console.log(`Training rows for ${tier}: ${subset.length}`);
  if (subset.length > 0) {
    collegeTrees[tier] = buildID3Tree(subset, attributes, "COLLEGE");
    console.log(`  Built COLLEGE tree for ${tier}`);
  } else {
    collegeTrees[tier] = null;
    console.log(`  No training rows for ${tier} -> no college tree`);
  }
}

// ----------------------
// Stage 2: Predict COLLEGES using predictedTier (funneling)
// For each test example: predict tier (done), then use collegeTrees[predictedTier] to predict college.
// We will evaluate college accuracy only on examples where predictedTier == actualTier (as per your idea)
// ----------------------
console.log(
  "\n--- Predicting COLLEGE for test examples (using predicted TIER funnel) ---"
);

let collegeCorrect_whenTierCorrect = 0;
let tierCorrectCount_forCollegeEval = 0;
let overallBothCorrect = 0;

// initialize per-tier college confusion matrices (rows = actual colleges for that tier)
function initCollegeMatrix(colleges) {
  const m = {};
  for (const a of colleges) {
    m[a] = {};
    // initialize columns for all possible predicted colleges (we'll accept predicted colleges possibly outside the tier)
    const allPossible = [...TOP_COLLEGES, ...MID_COLLEGES, ...LOW_COLLEGES];
    for (const p of allPossible) m[a][p] = 0;
  }
  return m;
}

const collegeMatrixTop = initCollegeMatrix(TOP_COLLEGES);
const collegeMatrixMid = initCollegeMatrix(MID_COLLEGES);
const collegeMatrixLow = initCollegeMatrix(LOW_COLLEGES);

for (const rec of testPredictions) {
  const ex = rec.example;
  const actualTier = ex.TIER;
  const actualCollege = ex.COLLEGE;
  const predTier = rec.predictedTier;

  // Predict college using the tree for the predicted tier
  const collegeTree = collegeTrees[predTier];
  let predCollege = null;
  if (collegeTree) {
    predCollege = classify(collegeTree, ex);
  } else {
    // fallback: majority of training subset for that predicted tier if exists, else overall majority
    const subset = trainingData.filter((r) => r.TIER === predTier);
    predCollege =
      subset.length > 0
        ? getMajorityClass(subset, "COLLEGE")
        : getMajorityClass(trainingData, "COLLEGE");
  }
  rec.predictedCollege = predCollege;

  // Update per-tier college matrices using actualTier (we only add rows for actual tier)
  if (actualTier === "Top") {
    collegeMatrixTop[actualCollege][predCollege] =
      (collegeMatrixTop[actualCollege][predCollege] || 0) + 1;
  } else if (actualTier === "Mid") {
    collegeMatrixMid[actualCollege][predCollege] =
      (collegeMatrixMid[actualCollege][predCollege] || 0) + 1;
  } else if (actualTier === "Low") {
    collegeMatrixLow[actualCollege][predCollege] =
      (collegeMatrixLow[actualCollege][predCollege] || 0) + 1;
  }

  // Evaluate college accuracy conditional on tier correctness
  if (predTier === actualTier) {
    tierCorrectCount_forCollegeEval++;
    if (predCollege === actualCollege) collegeCorrect_whenTierCorrect++;
  }

  // overall both correct?
  if (predTier === actualTier && predCollege === actualCollege)
    overallBothCorrect++;
}

// Print college matrices
console.log(
  "\n--- COLLEGE Confusion Matrix (Top tier; rows=actual top colleges) ---"
);
printMatrix(collegeMatrixTop, TOP_COLLEGES);

console.log(
  "\n--- COLLEGE Confusion Matrix (Mid tier; rows=actual mid colleges) ---"
);
printMatrix(collegeMatrixMid, MID_COLLEGES);

console.log(
  "\n--- COLLEGE Confusion Matrix (Low tier; rows=actual low colleges) ---"
);
printMatrix(collegeMatrixLow, LOW_COLLEGES);

// Print metrics
console.log("\n--- Evaluation Summary ---");
console.log("Total test examples:", testData.length);
console.log(
  `Tier correct: ${tierCorrect}/${testData.length} = ${(
    (tierCorrect / testData.length) *
    100
  ).toFixed(2)}%`
);
console.log(
  `Test rows where predicted Tier == actual Tier: ${tierCorrectCount_forCollegeEval}`
);
console.log(`College correct among those: ${collegeCorrect_whenTierCorrect}`);
const conditionalCollegeAcc =
  tierCorrectCount_forCollegeEval > 0
    ? collegeCorrect_whenTierCorrect / tierCorrectCount_forCollegeEval
    : 0;
console.log(
  `College Accuracy (conditional on tier correct): ${(
    conditionalCollegeAcc * 100
  ).toFixed(2)}%`
);
console.log(
  `Overall (both Tier & College correct): ${overallBothCorrect}/${
    testData.length
  } = ${((overallBothCorrect / testData.length) * 100).toFixed(2)}%`
);

// ----------------------
// Sample predictions (show all test with their predicted tier & college)
// ----------------------
console.log("\n--- Sample Predictions (all test examples) ---");
testPredictions.forEach((r, i) => {
  console.log(
    `Example ${i + 1}: Actual -> [Tier: ${r.example.TIER}, College: ${
      r.example.COLLEGE
    }]  Pred -> [Tier: ${r.predictedTier}, College: ${r.predictedCollege}]`
  );
});

console.log("\nDone.");
