const trainingData = [
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },

  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },

  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },

  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
];

// ============================================
// CORE ID3 ALGORITHM FUNCTIONS
// ============================================

function countFrequencies(data, attribute) {
  const counts = {};
  for (const example of data) {
    const value = example[attribute];
    counts[value] = (counts[value] || 0) + 1;
  }
  return counts;
}

function calculateEntropy(data, targetAttr) {
  if (data.length === 0) return 0;
  const classCounts = countFrequencies(data, targetAttr);
  const totalExamples = data.length;
  let entropy = 0;

  for (const count of Object.values(classCounts)) {
    const probability = count / totalExamples;
    entropy -= probability * Math.log2(probability);
  }
  return entropy;
}

function splitData(data, attribute) {
  const subsets = {};
  for (const example of data) {
    const value = example[attribute];
    if (!subsets[value]) {
      subsets[value] = [];
    }
    subsets[value].push(example);
  }
  return subsets;
}

function calculateInformationGain(data, attribute, targetAttr) {
  const initialEntropy = calculateEntropy(data, targetAttr);
  const subsets = splitData(data, attribute);
  const totalExamples = data.length;
  let remainingEntropy = 0;

  for (const subsetData of Object.values(subsets)) {
    const proportion = subsetData.length / totalExamples;
    const subsetEntropy = calculateEntropy(subsetData, targetAttr);
    remainingEntropy += proportion * subsetEntropy;
  }

  return initialEntropy - remainingEntropy;
}

function findBestSplitAttribute(data, attributes, targetAttr) {
  let maxGain = -Infinity;
  let bestAttribute = null;

  for (const attribute of attributes) {
    const gain = calculateInformationGain(data, attribute, targetAttr);
    if (gain > maxGain) {
      maxGain = gain;
      bestAttribute = attribute;
    }
  }

  return bestAttribute;
}

function getMajorityClass(data, targetAttr) {
  const classCounts = countFrequencies(data, targetAttr);
  let majorityClass = null;
  let maxCount = -1;

  for (const [className, count] of Object.entries(classCounts)) {
    if (count > maxCount) {
      maxCount = count;
      majorityClass = className;
    }
  }
  return majorityClass;
}

function buildID3Tree(data, availableAttributes, targetAttr) {
  if (calculateEntropy(data, targetAttr) === 0) {
    return { type: "leaf", class: data[0][targetAttr] };
  }

  if (availableAttributes.length === 0) {
    return { type: "leaf", class: getMajorityClass(data, targetAttr) };
  }

  const bestAttribute = findBestSplitAttribute(
    data,
    availableAttributes,
    targetAttr
  );

  if (!bestAttribute) {
    return { type: "leaf", class: getMajorityClass(data, targetAttr) };
  }

  const tree = {
    type: "node",
    attribute: bestAttribute,
    children: {},
  };

  const remainingAttributes = availableAttributes.filter(
    (attr) => attr !== bestAttribute
  );
  const subsets = splitData(data, bestAttribute);

  for (const [value, subset] of Object.entries(subsets)) {
    if (subset.length === 0) {
      tree.children[value] = {
        type: "leaf",
        class: getMajorityClass(data, targetAttr),
      };
    } else {
      tree.children[value] = buildID3Tree(
        subset,
        remainingAttributes,
        targetAttr
      );
    }
  }

  return tree;
}

function classify(tree, example) {
  if (tree.type === "leaf") {
    return tree.class;
  }

  const attributeValue = example[tree.attribute];
  const nextNode = tree.children[attributeValue];

  if (!nextNode) {
    console.warn(
      `No branch for attribute value '${attributeValue}' on attribute '${tree.attribute}'.`
    );
    return null;
  }

  return classify(nextNode, example);
}

// ============================================
// TWO-STAGE PREDICTION SYSTEM
// ============================================

// Stage 1: Build TIER prediction tree
const tierAttributes = [
  "SEE_GPA",
  "SEE_Science_GPA",
  "SEE_Math_GPA",
  "Fee",
  "Hostel",
  "Transportation",
  "ECA",
  "Scholarship",
  "Science_Labs",
  "Infrastructure",
];

const tierTree = buildID3Tree(trainingData, tierAttributes, "TIER");
console.log("=== STAGE 1: TIER Tree Built ===");
console.log("TIER Tree Structure:", JSON.stringify(tierTree, null, 2));

// Cache for TIER-specific college trees (to avoid rebuilding)
const collegeTreeCache = {};

/**
 * Filters training data by a specific TIER value
 */
function filterDataByTier(data, tierValue) {
  return data.filter((example) => example.TIER === tierValue);
}

/**
 * Builds a COLLEGE prediction tree for a specific TIER
 */
function buildCollegeTreeForTier(tierValue) {
  // Check cache first
  if (collegeTreeCache[tierValue]) {
    console.log(`  → Using cached COLLEGE tree for TIER: ${tierValue}`);
    return collegeTreeCache[tierValue];
  }

  console.log(`  → Building new COLLEGE tree for TIER: ${tierValue}`);

  // Filter training data to only this TIER
  const filteredData = filterDataByTier(trainingData, tierValue);

  if (filteredData.length === 0) {
    console.warn(`  → No training data found for TIER: ${tierValue}`);
    return null;
  }

  // Build tree with same attributes (excluding TIER and COLLEGE)
  const collegeAttributes = tierAttributes.filter((attr) => attr !== "TIER");

  const collegeTree = buildID3Tree(filteredData, collegeAttributes, "COLLEGE");

  // Cache the tree
  collegeTreeCache[tierValue] = collegeTree;

  return collegeTree;
}

/**
 * Main function: Predicts both TIER and COLLEGE for a student
 */
function predictCollegeWithTier(studentData) {
  console.log("\n=== TWO-STAGE PREDICTION ===");
  console.log("Student Data:", studentData);

  // STAGE 1: Predict TIER
  const predictedTier = classify(tierTree, studentData);
  console.log(`\n[Stage 1] Predicted TIER: ${predictedTier}`);

  if (!predictedTier) {
    return {
      predictedTier: null,
      predictedCollege: null,
      error: "Could not predict TIER",
    };
  }

  // STAGE 2: Build/Get COLLEGE tree for this TIER and predict
  const collegeTree = buildCollegeTreeForTier(predictedTier);

  if (!collegeTree) {
    return {
      predictedTier,
      predictedCollege: null,
      error: `No college tree available for TIER: ${predictedTier}`,
    };
  }

  const predictedCollege = classify(collegeTree, studentData);
  console.log(`[Stage 2] Predicted COLLEGE: ${predictedCollege}`);

  return {
    predictedTier,
    predictedCollege,
  };
}

// ============================================
// TESTING THE TWO-STAGE SYSTEM
// ============================================

console.log("\n\n========================================");
console.log("TESTING TWO-STAGE PREDICTION SYSTEM");
console.log("========================================");

// Test Case 1: Low tier student
const testStudent1 = {
  SEE_GPA: "2.0-2.8",
  SEE_Science_GPA: "<2.4",
  SEE_Math_GPA: "<2.4",
  Fee: "Low",
  Hostel: "No",
  Transportation: "No",
  ECA: "Weak",
  Scholarship: "No",
  Science_Labs: "Poor",
  Infrastructure: "Poor",
};

const result1 = predictCollegeWithTier(testStudent1);
console.log("\n✓ Final Result:", result1);

// Test Case 2: Top tier student
const testStudent2 = {
  SEE_GPA: ">3.6",
  SEE_Science_GPA: ">3.6",
  SEE_Math_GPA: ">3.6",
  Fee: "High",
  Hostel: "Yes",
  Transportation: "Yes",
  ECA: "Strong",
  Scholarship: "Yes",
  Science_Labs: "Good",
  Infrastructure: "Excellent",
};

const result2 = predictCollegeWithTier(testStudent2);
console.log("\n✓ Final Result:", result2);

// Test Case 3: Mid tier student
const testStudent3 = {
  SEE_GPA: "2.8-3.6",
  SEE_Science_GPA: "2.4-3.6",
  SEE_Math_GPA: "2.4-3.6",
  Fee: "Medium",
  Hostel: "Yes",
  Transportation: "No",
  ECA: "Strong",
  Scholarship: "Yes",
  Science_Labs: "Good",
  Infrastructure: "Average",
};

const result3 = predictCollegeWithTier(testStudent3);
console.log("\n✓ Final Result:", result3);

console.log("\n========================================");
console.log("CACHE STATUS");
console.log("========================================");
console.log("Cached TIER trees:", Object.keys(collegeTreeCache));
console.log("Total trees in cache:", Object.keys(collegeTreeCache).length);

// ============================================
// TEST DATA
// ============================================

const testData = [
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "NIST",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Xavier Academy",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "<2.4",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "KMC",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "<2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    TIER: "Low",
    COLLEGE: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "Prime",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    TIER: "Top",
    COLLEGE: "St. Xavier",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "<2.4",
    SEE_Math_GPA: "2.4-3.6",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    TIER: "Low",
    COLLEGE: "Herald",
  },
  {
    SEE_GPA: "2.8-3.6",
    SEE_Science_GPA: "2.4-3.6",
    SEE_Math_GPA: ">3.6",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    TIER: "Mid",
    COLLEGE: "V.S Niketan",
  },
];

// ============================================
// TWO-STAGE ACCURACY EVALUATION
// ============================================

function evaluateTwoStageSystem(testData) {
  console.log("\n\n========================================");
  console.log("TWO-STAGE SYSTEM EVALUATION");
  console.log("========================================");

  let tierCorrect = 0;
  let collegeCorrect = 0;
  let bothCorrect = 0;
  const total = testData.length;

  // Confusion matrices
  const tierConfusion = {};
  const collegeConfusion = {};

  // Track results
  const results = [];

  for (let i = 0; i < testData.length; i++) {
    const example = testData[i];
    const actualTier = example.TIER;
    const actualCollege = example.COLLEGE;

    // Make prediction
    const prediction = predictCollegeWithTier(example);
    const predictedTier = prediction.predictedTier;
    const predictedCollege = prediction.predictedCollege;

    // Track TIER accuracy
    if (predictedTier === actualTier) {
      tierCorrect++;
    }

    // Track COLLEGE accuracy
    if (predictedCollege === actualCollege) {
      collegeCorrect++;
    }

    // Track both correct
    if (predictedTier === actualTier && predictedCollege === actualCollege) {
      bothCorrect++;
    }

    // Build confusion matrix for TIER
    if (!tierConfusion[actualTier]) {
      tierConfusion[actualTier] = {};
    }
    tierConfusion[actualTier][predictedTier] =
      (tierConfusion[actualTier][predictedTier] || 0) + 1;

    // Build confusion matrix for COLLEGE
    if (!collegeConfusion[actualCollege]) {
      collegeConfusion[actualCollege] = {};
    }
    collegeConfusion[actualCollege][predictedCollege] =
      (collegeConfusion[actualCollege][predictedCollege] || 0) + 1;

    results.push({
      index: i + 1,
      actualTier,
      predictedTier,
      tierMatch: predictedTier === actualTier ? "✓" : "✗",
      actualCollege,
      predictedCollege,
      collegeMatch: predictedCollege === actualCollege ? "✓" : "✗",
    });
  }

  // Calculate accuracies
  const tierAccuracy = (tierCorrect / total) * 100;
  const collegeAccuracy = (collegeCorrect / total) * 100;
  const overallAccuracy = (bothCorrect / total) * 100;

  console.log("\n--- STAGE 1: TIER PREDICTION RESULTS ---");
  console.log(`Total Test Cases: ${total}`);
  console.log(`Correct TIER Predictions: ${tierCorrect}`);
  console.log(`TIER Accuracy: ${tierAccuracy.toFixed(2)}%`);

  console.log("\n--- STAGE 2: COLLEGE PREDICTION RESULTS ---");
  console.log(`Correct COLLEGE Predictions: ${collegeCorrect}`);
  console.log(`COLLEGE Accuracy: ${collegeAccuracy.toFixed(2)}%`);

  console.log("\n--- OVERALL TWO-STAGE ACCURACY ---");
  console.log(`Both TIER and COLLEGE Correct: ${bothCorrect}`);
  console.log(`Overall System Accuracy: ${overallAccuracy.toFixed(2)}%`);

  // Print detailed results table
  console.log("\n--- DETAILED PREDICTION RESULTS ---");
  console.log(
    "Test | Actual TIER | Pred TIER | ✓/✗ | Actual COLLEGE | Pred COLLEGE | ✓/✗"
  );
  console.log("-".repeat(90));
  for (const r of results) {
    console.log(
      `${String(r.index).padStart(4)} | ${r.actualTier.padEnd(
        11
      )} | ${r.predictedTier.padEnd(9)} | ${r.tierMatch.padEnd(
        3
      )} | ${r.actualCollege.padEnd(14)} | ${(
        r.predictedCollege || "NULL"
      ).padEnd(12)} | ${r.collegeMatch}`
    );
  }

  // Print TIER confusion matrix
  console.log("\n--- STAGE 1: TIER CONFUSION MATRIX ---");
  printConfusionMatrix(tierConfusion, ["Top", "Mid", "Low"]);

  // Print COLLEGE confusion matrix
  console.log("\n--- STAGE 2: COLLEGE CONFUSION MATRIX ---");
  const allColleges = [...new Set(testData.map((d) => d.COLLEGE))].sort();
  printConfusionMatrix(collegeConfusion, allColleges);

  // Calculate per-class metrics for TIER
  console.log("\n--- STAGE 1: TIER METRICS PER CLASS ---");
  const tierMetrics = calculatePerClassMetrics(tierConfusion, [
    "Top",
    "Mid",
    "Low",
  ]);
  printPerClassMetrics(tierMetrics);

  // Calculate per-class metrics for COLLEGE
  console.log("\n--- STAGE 2: COLLEGE METRICS PER CLASS ---");
  const collegeMetrics = calculatePerClassMetrics(
    collegeConfusion,
    allColleges
  );
  printPerClassMetrics(collegeMetrics);

  return {
    tierAccuracy,
    collegeAccuracy,
    overallAccuracy,
    tierCorrect,
    collegeCorrect,
    bothCorrect,
    total,
    results,
  };
}

function printConfusionMatrix(matrix, classes) {
  let header = "ACTUAL \\ PREDICTED |";
  for (const pClass of classes) {
    header += ` ${pClass.padEnd(12)} |`;
  }
  console.log(header);
  console.log("-".repeat(header.length));

  for (const aClass of classes) {
    let row = `${aClass.padEnd(18)}|`;
    for (const pClass of classes) {
      const count = matrix[aClass] ? matrix[aClass][pClass] || 0 : 0;
      row += ` ${String(count).padEnd(12)} |`;
    }
    console.log(row);
  }
}

function calculatePerClassMetrics(matrix, classes) {
  const metrics = {};

  for (const targetClass of classes) {
    const TP = matrix[targetClass] ? matrix[targetClass][targetClass] || 0 : 0;

    let FP = 0;
    for (const aClass of classes) {
      if (aClass !== targetClass && matrix[aClass]) {
        FP += matrix[aClass][targetClass] || 0;
      }
    }

    let FN = 0;
    if (matrix[targetClass]) {
      for (const pClass of classes) {
        if (pClass !== targetClass) {
          FN += matrix[targetClass][pClass] || 0;
        }
      }
    }

    const precision = TP + FP > 0 ? TP / (TP + FP) : 0;
    const recall = TP + FN > 0 ? TP / (TP + FN) : 0;
    const f1 =
      precision + recall > 0
        ? (2 * precision * recall) / (precision + recall)
        : 0;

    metrics[targetClass] = { TP, FP, FN, precision, recall, f1 };
  }

  return metrics;
}

function printPerClassMetrics(metrics) {
  console.log(
    "Class            | TP  | FP  | FN  | Precision | Recall   | F1-Score"
  );
  console.log("-".repeat(75));
  for (const [className, m] of Object.entries(metrics)) {
    console.log(
      `${className.padEnd(16)} | ${String(m.TP).padEnd(3)} | ${String(
        m.FP
      ).padEnd(3)} | ${String(m.FN).padEnd(3)} | ${m.precision
        .toFixed(4)
        .padEnd(9)} | ${m.recall.toFixed(4).padEnd(8)} | ${m.f1.toFixed(4)}`
    );
  }
}

// ============================================
// RUN EVALUATION
// ============================================

const evaluationResults = evaluateTwoStageSystem(testData);

console.log("\n\n========================================");
console.log("FINAL SUMMARY");
console.log("========================================");
console.log(
  `📊 Stage 1 (TIER) Accuracy: ${evaluationResults.tierAccuracy.toFixed(2)}%`
);
console.log(
  `📊 Stage 2 (COLLEGE) Accuracy: ${evaluationResults.collegeAccuracy.toFixed(
    2
  )}%`
);
console.log(
  `📊 Overall System Accuracy: ${evaluationResults.overallAccuracy.toFixed(2)}%`
);
console.log(
  `✓ Both Predictions Correct: ${evaluationResults.bothCorrect}/${evaluationResults.total}`
);
