// ============================================
// FULL DATASET
// ============================================

//
// 🔴 IMPORTANT: REPLACE THIS with your full 350-example dataset.
//
const allData = [
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Central",
    College: "Sagarmatha",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "KMC",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Prime",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Central",
    College: "Times",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Outskirts",
    College: "St. Xavier's",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Takshashila",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Outskirts",
    College: "VS Niketan",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Peripheral",
    College: "NIST",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "No",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Good",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Medium",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Average",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Xavier Academy",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: ">3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "High",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "No",
    Science_Labs: "Excellent",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "3.2-3.6",
    SEE_Science_GPA: ">3.2",
    SEE_Math_GPA: ">3.2",
    Fee: "High",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Strong",
    Scholarship: "Yes",
    Science_Labs: "Good",
    Infrastructure: "Excellent",
    College_Location: "Central",
    College: "Trinity",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "No",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.0-2.8",
    SEE_Science_GPA: "2.4-3.2",
    SEE_Math_GPA: "2.0-2.4",
    Fee: "Low",
    Hostel: "No",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "Yes",
    Science_Labs: "Poor",
    Infrastructure: "Poor",
    College_Location: "Peripheral",
    College: "Herald",
  },
  {
    SEE_GPA: "2.8-3.2",
    SEE_Science_GPA: "2.0-2.4",
    SEE_Math_GPA: "2.4-3.2",
    Fee: "Low",
    Hostel: "Yes",
    Transportation: "Yes",
    ECA: "Weak",
    Scholarship: "No",
    Science_Labs: "Poor",
    Infrastructure: "Average",
    College_Location: "Peripheral",
    College: "Herald",
  },
];

const targetAttribute = "College";

const attributes = [
  "SEE_GPA",
  "SEE_Science_GPA",
  "SEE_Math_GPA",
  "Fee",
  "Hostel",
  "Transportation",
  "ECA",
  "Scholarship",
  "Science_Labs",
  "Infrastructure",
  "College_Location",
];

const allCollegeClasses = [...new Set(allData.map((d) => d.College))].sort();

// ============================================
// 🚀 TUNING & CONFIGURATION
// ============================================

const K_FOLDS = 10;
const PRUNING_MAX_DEPTH = 7;
const PRUNING_MIN_SAMPLES_SPLIT = 10;

// ✨ NEW: Minimum information gain threshold
const MIN_INFORMATION_GAIN = 0.01; // Stop splitting if gain is too small

// ============================================
// IMPROVED: findBestSplitAttribute
// ============================================

/**
 * Finds the attribute with highest Information Gain.
 * ✨ FIXED: Now returns null if best gain is below threshold
 */
function findBestSplitAttribute(data, attributes, targetAttr) {
  let maxGain = -Infinity;
  let bestAttribute = null;

  for (const attribute of attributes) {
    const gain = calculateInformationGain(data, attribute, targetAttr);
    if (gain > maxGain) {
      maxGain = gain;
      bestAttribute = attribute;
    }
  }

  // ✨ FIX: Check if information gain is meaningful
  if (maxGain < MIN_INFORMATION_GAIN) {
    return null; // No attribute provides useful information
  }

  return bestAttribute;
}

// ============================================
// IMPROVED: buildID3Tree with better logging
// ============================================

function buildID3Tree(
  data,
  availableAttributes,
  targetAttr,
  maxDepth = 10,
  minSamplesSplit = 5,
  depth = 0 // Track current depth for debugging
) {
  // --- PRE-PRUNING BASE CASES ---
  if (maxDepth <= 0) {
    return {
      type: "leaf",
      class: getMajorityClass(data, targetAttr),
      reason: "max_depth",
      samples: data.length,
    };
  }

  if (data.length < minSamplesSplit) {
    return {
      type: "leaf",
      class: getMajorityClass(data, targetAttr),
      reason: "min_samples",
      samples: data.length,
    };
  }

  // --- ORIGINAL BASE CASES ---
  const entropy = calculateEntropy(data, targetAttr);
  if (entropy === 0) {
    return {
      type: "leaf",
      class: data[0][targetAttr],
      reason: "pure",
      samples: data.length,
    };
  }

  if (availableAttributes.length === 0) {
    return {
      type: "leaf",
      class: getMajorityClass(data, targetAttr),
      reason: "no_attributes",
      samples: data.length,
    };
  }

  // --- RECURSION ---
  const bestAttribute = findBestSplitAttribute(
    data,
    availableAttributes,
    targetAttr
  );

  // ✨ IMPROVED: Better handling of no information gain
  if (!bestAttribute) {
    return {
      type: "leaf",
      class: getMajorityClass(data, targetAttr),
      reason: "no_gain",
      samples: data.length,
      entropy: entropy.toFixed(4),
    };
  }

  const tree = {
    type: "node",
    attribute: bestAttribute,
    children: {},
    majorityClass: getMajorityClass(data, targetAttr),
    depth: depth,
    samples: data.length,
    entropy: entropy.toFixed(4),
  };

  const remainingAttributes = availableAttributes.filter(
    (attr) => attr !== bestAttribute
  );
  const subsets = splitData(data, bestAttribute);

  for (const [value, subset] of Object.entries(subsets)) {
    if (subset.length === 0) {
      tree.children[value] = {
        type: "leaf",
        class: tree.majorityClass,
        reason: "empty_subset",
        samples: 0,
      };
    } else {
      tree.children[value] = buildID3Tree(
        subset,
        remainingAttributes,
        targetAttr,
        maxDepth - 1,
        minSamplesSplit,
        depth + 1 // Increment depth
      );
    }
  }

  return tree;
}

// ============================================
// NEW: Tree Statistics Function
// ============================================

function analyzeTree(
  tree,
  stats = { leaves: 0, nodes: 0, maxDepth: 0, reasons: {} }
) {
  if (tree.type === "leaf") {
    stats.leaves++;
    const reason = tree.reason || "unknown";
    stats.reasons[reason] = (stats.reasons[reason] || 0) + 1;
    return stats;
  }

  stats.nodes++;
  stats.maxDepth = Math.max(stats.maxDepth, tree.depth || 0);

  for (const child of Object.values(tree.children)) {
    analyzeTree(child, stats);
  }

  return stats;
}

// ============================================
// IMPROVED: Cross-Validation with Tree Analysis
// ============================================

function performKFoldCrossValidation(
  fullData,
  k,
  featureAttributes,
  targetAttr,
  allClasses
) {
  console.log(`\n\n========================================`);
  console.log(`🚀 STARTING ${k}-FOLD CROSS-VALIDATION`);
  console.log(`Total examples: ${fullData.length}`);
  console.log(
    `Pruning: maxDepth=${PRUNING_MAX_DEPTH}, minSamplesSplit=${PRUNING_MIN_SAMPLES_SPLIT}`
  );
  console.log(`Min Info Gain: ${MIN_INFORMATION_GAIN}`);
  console.log(`========================================`);

  shuffleArray(fullData);

  const foldSize = Math.ceil(fullData.length / k);
  const folds = [];
  for (let i = 0; i < fullData.length; i += foldSize) {
    folds.push(fullData.slice(i, i + foldSize));
  }
  if (folds.length > k) {
    const lastFold = folds.pop();
    folds[k - 1] = folds[k - 1].concat(lastFold);
  }

  let aggregatedCollegeConfusion = {};
  let totalCorrectCollege = 0;
  let totalProcessed = 0;
  let allTreeStats = [];

  for (let i = 0; i < folds.length; i++) {
    console.log(`\n--- FOLD ${i + 1} / ${k} ---`);

    const testData = folds[i];
    const trainingData = folds
      .slice(0, i)
      .concat(folds.slice(i + 1))
      .flat();
    console.log(
      `Training size: ${trainingData.length}, Test size: ${testData.length}`
    );

    if (trainingData.length === 0 || testData.length === 0) {
      console.warn("Skipping fold, not enough data for train/test split.");
      continue;
    }

    // Train Model
    const CollegeTree = buildID3Tree(
      trainingData,
      featureAttributes,
      targetAttr,
      PRUNING_MAX_DEPTH,
      PRUNING_MIN_SAMPLES_SPLIT
    );

    // ✨ NEW: Analyze tree structure
    const treeStats = analyzeTree(CollegeTree);
    allTreeStats.push(treeStats);
    console.log(
      `Tree: ${treeStats.nodes} nodes, ${treeStats.leaves} leaves, max depth: ${treeStats.maxDepth}`
    );

    // Evaluate
    const foldCollegeConfusion = {};
    let foldCollegeCorrect = 0;

    for (const example of testData) {
      const actualCollege = example[targetAttr];
      const predictedCollege = classify(CollegeTree, example);

      if (predictedCollege === actualCollege) foldCollegeCorrect++;

      if (!foldCollegeConfusion[actualCollege])
        foldCollegeConfusion[actualCollege] = {};
      foldCollegeConfusion[actualCollege][predictedCollege] =
        (foldCollegeConfusion[actualCollege][predictedCollege] || 0) + 1;
    }

    aggregateConfusionMatrix(aggregatedCollegeConfusion, foldCollegeConfusion);
    totalCorrectCollege += foldCollegeCorrect;
    totalProcessed += testData.length;

    const foldCollegeAcc = (foldCollegeCorrect / testData.length) * 100;
    console.log(
      `Fold ${i + 1} College Accuracy: ${foldCollegeAcc.toFixed(2)}%`
    );
  }

  // Report results
  console.log(`\n\n========================================`);
  console.log(`📊 K-FOLD CROSS-VALIDATION SUMMARY`);
  console.log(`========================================`);

  const avgCollegeAcc = (totalCorrectCollege / totalProcessed) * 100;

  console.log(`\n--- OVERALL ACCURACY (MICRO-AVERAGE) ---`);
  console.log(`Total Predictions: ${totalProcessed}`);
  console.log(
    `College Accuracy: ${avgCollegeAcc.toFixed(
      2
    )}% (${totalCorrectCollege}/${totalProcessed})`
  );

  // ✨ NEW: Average tree statistics
  console.log(`\n--- AVERAGE TREE STATISTICS ---`);
  const avgNodes =
    allTreeStats.reduce((s, t) => s + t.nodes, 0) / allTreeStats.length;
  const avgLeaves =
    allTreeStats.reduce((s, t) => s + t.leaves, 0) / allTreeStats.length;
  const avgMaxDepth =
    allTreeStats.reduce((s, t) => s + t.maxDepth, 0) / allTreeStats.length;
  console.log(`Avg Nodes: ${avgNodes.toFixed(1)}`);
  console.log(`Avg Leaves: ${avgLeaves.toFixed(1)}`);
  console.log(`Avg Max Depth: ${avgMaxDepth.toFixed(1)}`);

  console.log("\n--- AGGREGATED COLLEGE CONFUSION MATRIX ---");
  printConfusionMatrix(aggregatedCollegeConfusion, allClasses);

  console.log("\n--- AGGREGATED COLLEGE METRICS PER CLASS ---");
  const CollegeMetrics = calculatePerClassMetrics(
    aggregatedCollegeConfusion,
    allClasses
  );
  printPerClassMetrics(CollegeMetrics);

  console.log("\n========================================");
  console.log("✅ Cross-Validation Complete.");
  console.log("========================================");
}

// ============================================
// HELPER FUNCTIONS (same as before)
// ============================================

function countFrequencies(data, attribute) {
  const counts = {};
  for (const example of data) {
    const value = example[attribute];
    counts[value] = (counts[value] || 0) + 1;
  }
  return counts;
}

function calculateEntropy(data, targetAttr) {
  if (data.length === 0) return 0;
  const classCounts = countFrequencies(data, targetAttr);
  const totalExamples = data.length;
  let entropy = 0;

  for (const count of Object.values(classCounts)) {
    const probability = count / totalExamples;
    entropy -= probability * Math.log2(probability);
  }
  return entropy;
}

function splitData(data, attribute) {
  const subsets = {};
  for (const example of data) {
    const value = example[attribute];
    if (!subsets[value]) {
      subsets[value] = [];
    }
    subsets[value].push(example);
  }
  return subsets;
}

function calculateInformationGain(data, attribute, targetAttr) {
  const initialEntropy = calculateEntropy(data, targetAttr);
  const subsets = splitData(data, attribute);
  const totalExamples = data.length;
  let remainingEntropy = 0;

  for (const subsetData of Object.values(subsets)) {
    const proportion = subsetData.length / totalExamples;
    const subsetEntropy = calculateEntropy(subsetData, targetAttr);
    remainingEntropy += proportion * subsetEntropy;
  }

  return initialEntropy - remainingEntropy;
}

function getMajorityClass(data, targetAttr) {
  const classCounts = countFrequencies(data, targetAttr);
  let majorityClass = null;
  let maxCount = -1;

  for (const [className, count] of Object.entries(classCounts)) {
    if (count > maxCount) {
      maxCount = count;
      majorityClass = className;
    }
  }
  return majorityClass;
}

function classify(tree, example) {
  if (tree.type === "leaf") {
    return tree.class;
  }

  const attributeValue = example[tree.attribute];
  const nextNode = tree.children[attributeValue];

  if (!nextNode) {
    return tree.majorityClass;
  }

  return classify(nextNode, example);
}

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

function aggregateConfusionMatrix(aggMatrix, foldMatrix) {
  for (const actual in foldMatrix) {
    if (!aggMatrix[actual]) aggMatrix[actual] = {};
    for (const predicted in foldMatrix[actual]) {
      aggMatrix[actual][predicted] =
        (aggMatrix[actual][predicted] || 0) + foldMatrix[actual][predicted];
    }
  }
}

function printConfusionMatrix(matrix, classes) {
  const padding = Math.max(12, ...classes.map((c) => (c ? c.length : 4)));

  let header = `ACTUAL \\ PRED`.padEnd(padding + 2) + "|";
  for (const pClass of classes) {
    header += ` ${(pClass || "null").padEnd(padding)} |`;
  }
  console.log(header);
  console.log("-".repeat(header.length));

  for (const aClass of classes) {
    let row = `${(aClass || "null").padEnd(padding + 2)}|`;
    for (const pClass of classes) {
      const count = matrix[aClass] ? matrix[aClass][pClass] || 0 : 0;
      row += ` ${String(count).padEnd(padding)} |`;
    }
    console.log(row);
  }
}

function calculatePerClassMetrics(matrix, classes) {
  const metrics = {};
  let totalTP = 0;
  let totalFP = 0;
  let totalFN = 0;

  for (const targetClass of classes) {
    const TP = matrix[targetClass] ? matrix[targetClass][targetClass] || 0 : 0;

    let FP = 0;
    for (const aClass of classes) {
      if (aClass !== targetClass && matrix[aClass]) {
        FP += matrix[aClass][targetClass] || 0;
      }
    }

    let FN = 0;
    if (matrix[targetClass]) {
      for (const pClass of classes) {
        if (pClass !== targetClass) {
          FN += matrix[targetClass][pClass] || 0;
        }
      }
    }

    totalTP += TP;
    totalFP += FP;
    totalFN += FN;

    const precision = TP + FP > 0 ? TP / (TP + FP) : 0;
    const recall = TP + FN > 0 ? TP / (TP + FN) : 0;
    const f1 =
      precision + recall > 0
        ? (2 * precision * recall) / (precision + recall)
        : 0;

    metrics[targetClass] = { TP, FP, FN, precision, recall, f1 };
  }

  const numClasses = classes.length;
  const macroPrecision =
    Object.values(metrics).reduce((sum, m) => sum + m.precision, 0) /
    numClasses;
  const macroRecall =
    Object.values(metrics).reduce((sum, m) => sum + m.recall, 0) / numClasses;
  const macroF1 =
    Object.values(metrics).reduce((sum, m) => sum + m.f1, 0) / numClasses;

  metrics["MACRO_AVG"] = {
    TP: "n/a",
    FP: "n/a",
    FN: "n/a",
    precision: macroPrecision,
    recall: macroRecall,
    f1: macroF1,
  };

  return metrics;
}

function printPerClassMetrics(metrics) {
  const classPadding = Math.max(
    16,
    ...Object.keys(metrics).map((k) => k.length)
  );

  console.log(
    `${"Class".padEnd(
      classPadding
    )} | TP  | FP  | FN  | Precision | Recall   | F1-Score`
  );
  console.log("-".repeat(classPadding + 50));

  for (const [className, m] of Object.entries(metrics)) {
    if (className === "MACRO_AVG") {
      console.log("-".repeat(classPadding + 50));
    }
    console.log(
      `${className.padEnd(classPadding)} | ${String(m.TP).padEnd(3)} | ${String(
        m.FP
      ).padEnd(3)} | ${String(m.FN).padEnd(3)} | ${m.precision
        .toFixed(4)
        .padEnd(9)} | ${m.recall.toFixed(4).padEnd(8)} | ${m.f1.toFixed(4)}`
    );
  }
}

performKFoldCrossValidation(
  allData,
  K_FOLDS,
  attributes,
  targetAttribute,
  allCollegeClasses
);

// ============================================
// (OLD CODE - COMMENTED OUT)
// ============================================

/*
// --- These console logs are good for debugging, but not needed for CV ---
console.log(
  "Initial Entropy:",
  calculateEntropy(allData, targetAttribute)
);
console.log(
  "Best Initial Attribute:",
  findBestSplitAttribute(allData, attributes, targetAttribute)
);
const majority = getMajorityClass(allData, "College");
console.log("Majority Class:", majority);
*/

/*
// --- Building a single tree on all data is replaced by K-Fold CV ---
const decisionTree = buildID3Tree(allData, attributes, targetAttribute);
console.log("--- The final ID3 Decision Tree structure ---");
console.log(JSON.stringify(decisionTree, null, 2));
*/

/*
// --- Single prediction test is replaced by K-Fold CV ---
const newExample = {
  SEE_GPA: "2.0-2.8",
  SEE_Science_GPA: "2.4-3.2",
  SEE_Math_GPA: "2.4-3.2",
  Fee: "Low",
  Hostel: "No",
  Transportation: "Yes",
  ECA: "Weak",
  Scholarship: "Yes",
  Science_Labs: "Poor",
  Infrastructure: "Average",
  College_Location: "Peripheral",
};
const prediction = classify(decisionTree, newExample);

console.log("\n--- Prediction Test ---");
console.log("Example:", newExample);
console.log("Predicted Class:", prediction);
*/
